import Head from "next/head";
import styles from "src/styles/Home.module.css";
import { Footer } from "src/components/Footer";
import { Main } from "src/components/Main";
import { Header } from "src/components/Header";

export default function Home(props) {
  console.log("props", props);

  const {
    isShow,
    count,
    handleClick,
    handleDisplay,
    handleChange,
    handleAdd,
    text,
    array,
  } = props;

  console.log(isShow);

  return (
    <div className={styles.container}>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      {/* {isShow ? <h1>{count}</h1> : null}
      <button onClick={handleClick}>Button</button>
      <button onClick={handleDisplay}>{isShow ? "非表示" : "表示"}</button>
      <input type="text" value={text} onChange={handleChange} />
      <button onClick={handleAdd}>追加</button>
      <ul>
        {array.map((item) => {
          return <li key={item}>{item}</li>;
        })}
      </ul> */}
      <Main page="index" />
      <Footer />
    </div>
  );
}
